### ISSUE TITLE
Change references to "Signal Choice" to "High Level Objective (HILO)"

### ISSUE THREAD

**Issue by UI369** [HausDAO/publichaus#25]
The language we use in the docs for the "choices" is "High Level Objective" or "HILO" or "Objective" for short. 

The site is saying "Create a choice for this Signal. You must be a member of the DAO to create a choice."

Change to "Create a new High Level Objective (HILO). You must be a member of the DAO to create a HILO."

Change page name "add-choice" to "add-objective"
or similar.

live pages: 
https://signal.daohaus.fun/#/tcr/0x48538a34d243856345af9389617c31e795377c1a

https://signal.daohaus.fun/#/tcr/0x48538a34d243856345af9389617c31e795377c1a/add-choice

**Comment by dekanbro** [comment]
should be reposted to a different repo
